#!/bin/bash

set -euo pipefail

# Set timezone to BST
echo 'ZONE="Europe/London"' > /etc/sysconfig/clock
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime

# Set system limits
cp /vagrant/files/90-nproc.conf /etc/security/limits.d/

# Disable unwanted services
for i in rpcbind nfslock iptables ip6tables; do
  service $i stop; chkconfig $i off
done

# Passwordless SSH setup
cp -r /vagrant/files/.ssh ~vagrant/
chown -R vagrant:vagrant ~vagrant/.ssh
chmod 700 ~vagrant/.ssh && chmod 600 ~vagrant/.ssh/*

# Update packages and remove/install some additional ones
yum -y remove postfix
yum -y update
yum -y install http://epel.check-update.co.uk/6/i386/epel-release-6-8.noarch.rpm
yum -y install htop bash-completion git vim

# Java setup
wget -N -nv --no-cookies -P /vagrant/files \
  --header "Cookie: oraclelicense=accept-securebackup-cookie" \
  "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.tar.gz"
mkdir -p /usr/java
tar -C /usr/java --no-same-owner -zxvf /vagrant/files/jdk-7u79-linux-x64.tar.gz
ln -s /usr/java/jdk1.7.0_79 /usr/java/default

# Privoxy setup
yum -y install privoxy
sed -i 's/listen-address.*127.0.0.1:8118/listen-address :8118/' /etc/privoxy/config
service privoxy start

# Latest docker setup
groupadd docker && usermod -aG docker vagrant
yum -y install --enablerepo=epel-testing docker-io
sed -i 's/other_args=/other_args="-s btrfs"/' /etc/sysconfig/docker
wget -N -nv -P /vagrant/files \
  https://get.docker.com/builds/Linux/x86_64/docker-latest
cp /vagrant/files/docker-latest /usr/bin/docker
chmod +x /usr/bin/docker
chkconfig docker on && service docker start
docker build -t peterpakos/centos /vagrant/

# Latest dockermaster setup
git clone https://github.com/peterpakos/dockermaster.git \
  /opt/dockermaster
ln -s /opt/dockermaster/dockermaster /usr/local/bin/dockermaster
